apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: funbox
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: funbox
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 99
