apiVersion: v1
kind: Service
metadata:
  name: funbox
  labels:
    app: funbox
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: funbox
